#!/usr/bin/env bash
# setup.sh — one-shot iOS project materialisation.
# Run after cloning so the generated AcmeBank.xcodeproj is created and
# opened in Xcode.
set -euo pipefail

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "Installing XcodeGen via Homebrew (one-time)…"
  brew install xcodegen
fi

mkdir -p Config

# Generate Config/Secrets.local.xcconfig from env vars (if any are set).
# This file is gitignored and is `#include?`d by the committed
# Config/Secrets.example.xcconfig — values here override the placeholder
# defaults. Xcode then expands $(OKTA_*) / $(API_BASE_URL) refs in
# AcmeBank/Info.plist on every build via ProcessInfoPlistFile (no
# post-build mutation needed).
#
# xcconfig gotcha: `://` must be escaped as `:/$()/` because a bare `//`
# in an xcconfig starts an end-of-line comment.
escape_xcconfig() { printf '%s' "$1" | sed 's|://|:/$()/|g'; }

if [ -n "${OKTA_ISSUER:-}${OKTA_CLIENT_ID:-}${OKTA_REDIRECT_URI:-}${OKTA_SCOPES:-}${API_BASE_URL:-}" ]; then
  {
    echo "// Auto-generated by setup.sh — DO NOT COMMIT"
    [ -n "${OKTA_ISSUER:-}"       ] && echo "OKTA_ISSUER = $(escape_xcconfig "$OKTA_ISSUER")"
    [ -n "${OKTA_CLIENT_ID:-}"    ] && echo "OKTA_CLIENT_ID = $OKTA_CLIENT_ID"
    [ -n "${OKTA_REDIRECT_URI:-}" ] && echo "OKTA_REDIRECT_URI = $(escape_xcconfig "$OKTA_REDIRECT_URI")"
    [ -n "${OKTA_SCOPES:-}"       ] && echo "OKTA_SCOPES = $OKTA_SCOPES"
    [ -n "${API_BASE_URL:-}"      ] && echo "API_BASE_URL = $(escape_xcconfig "$API_BASE_URL")"
  } > Config/Secrets.local.xcconfig
  echo "✓ Config/Secrets.local.xcconfig written."
else
  echo "ℹ No OKTA_* / API_BASE_URL env vars set — Secrets.local.xcconfig not created; app will show 'not configured' banners."
fi

echo "Generating AcmeBank.xcodeproj from project.yml…"
xcodegen generate

open -a Xcode AcmeBank.xcodeproj 2>/dev/null || \
  echo "✓ Project generated. Open AcmeBank.xcodeproj in Xcode to start."
