#!/usr/bin/env bash
# setup.sh — one-shot iOS project materialisation.
# Run after cloning so the generated AcmeBank.xcodeproj is created and
# opened in Xcode.
set -euo pipefail

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "Installing XcodeGen via Homebrew (one-time)…"
  brew install xcodegen
fi

mkdir -p Config

# Generate Config/Secrets.local.xcconfig from env vars (if any are set).
# This file is gitignored and is `#include?`d by the committed
# Config/Secrets.example.xcconfig — values here override the placeholder
# defaults. Xcode then expands $(OKTA_*) / $(API_BASE_URL) refs in
# AcmeBank/Info.plist on every build via ProcessInfoPlistFile (no
# post-build mutation needed).
#
# xcconfig gotcha: `://` must be escaped as `:/$()/` because a bare `//`
# in an xcconfig starts an end-of-line comment.
escape_xcconfig() { printf '%s' "$1" | sed 's|://|:/$()/|g'; }

# MERGE, never clobber: an exported env var wins, but a key already present
# in Secrets.local.xcconfig is PRESERVED when its env var is unset. A partial
# environment must never silently delete working config — 2026-07-03: a
# re-run with only OKTA_* exported dropped API_BASE_URL and re-broke Home
# with the "not configured" fail-fast.
#   $1 = key name; $2 = env value ("" when unset).
# Existing file values are already xcconfig-escaped; env values get escaped.
resolve_key() {
  if [ -n "$2" ]; then
    escape_xcconfig "$2"
  elif [ -f Config/Secrets.local.xcconfig ]; then
    # sed exits 0 on an existing file even with no match; guarding on the
    # file's existence keeps `set -euo pipefail` happy on a FRESH clone
    # (an unguarded sed on a missing path fails the command substitution
    # and kills the whole script before the first write).
    sed -n "s/^$1 *= *//p" Config/Secrets.local.xcconfig | tail -1
  fi
}

V_OKTA_ISSUER=$(resolve_key OKTA_ISSUER "${OKTA_ISSUER:-}")
V_OKTA_CLIENT_ID=$(resolve_key OKTA_CLIENT_ID "${OKTA_CLIENT_ID:-}")
V_OKTA_REDIRECT_URI=$(resolve_key OKTA_REDIRECT_URI "${OKTA_REDIRECT_URI:-}")
V_OKTA_SCOPES=$(resolve_key OKTA_SCOPES "${OKTA_SCOPES:-}")
V_API_BASE_URL=$(resolve_key API_BASE_URL "${API_BASE_URL:-}")

if [ -n "${V_OKTA_ISSUER}${V_OKTA_CLIENT_ID}${V_OKTA_REDIRECT_URI}${V_OKTA_SCOPES}${V_API_BASE_URL}" ]; then
  {
    echo "// Auto-generated by setup.sh — DO NOT COMMIT"
    echo "// Merge semantics: exported env vars win; keys already in this file"
    echo "// survive runs where their env var is unset."
    [ -n "$V_OKTA_ISSUER"       ] && echo "OKTA_ISSUER = $V_OKTA_ISSUER"
    [ -n "$V_OKTA_CLIENT_ID"    ] && echo "OKTA_CLIENT_ID = $V_OKTA_CLIENT_ID"
    [ -n "$V_OKTA_REDIRECT_URI" ] && echo "OKTA_REDIRECT_URI = $V_OKTA_REDIRECT_URI"
    [ -n "$V_OKTA_SCOPES"       ] && echo "OKTA_SCOPES = $V_OKTA_SCOPES"
    [ -n "$V_API_BASE_URL"      ] && echo "API_BASE_URL = $V_API_BASE_URL"
  } > Config/Secrets.local.xcconfig
  echo "✓ Config/Secrets.local.xcconfig written (env vars merged with existing values)."
else
  echo "ℹ No OKTA_* / API_BASE_URL env vars set and no existing values to preserve — Secrets.local.xcconfig not created; app will show 'not configured' banners."
fi

echo "Generating AcmeBank.xcodeproj from project.yml…"
xcodegen generate

open -a Xcode AcmeBank.xcodeproj 2>/dev/null || \
  echo "✓ Project generated. Open AcmeBank.xcodeproj in Xcode to start."
