#!/usr/bin/env python3
"""Self-contained contract-conformance gate (MothershipCode Phase 4a).

Generated by the MothershipCode CI/CD hardener and COMMITTED into this repo. It
is the consumer repo's own CI re-running the cross-tier codegen and diffing the
result against the committed ``Generated/`` tree — so contract drift (including a
human or non-agent edit to a generated DTO, or a tampered committed spec) is
caught on the PR, not at runtime.

This script is deliberately:

  * **registry-free** — it has NO access to the MothershipCode contract registry
    or DB. It discovers boundaries purely from disk, by the UNION of three
    signals: a committed ``Generated/<slug>/.contractgen.json`` manifest, any
    generated ``Generated/<slug>/*.swift`` / ``*.java`` source, or a committed
    ``contracts/<slug>.openapi.yaml`` spec — so deleting just the manifest can't
    make a hand-edited tree vanish from the gate. The committed spec is the
    source it re-generates from.
  * **diff-only** — it re-generates typed models into a TEMP dir with the pinned
    openapi-generator and compares; it NEVER edits the committed tree and NEVER
    compiles anything.
  * **skip-not-block when it cannot run** — if ``java`` / the JAR / the spec is
    missing it prints a clear note and exits 0 (mirrors the engine's
    ``CodegenError == SKIP``), so a runner without the generator can never
    falsely block a PR.

It mirrors ``app/services/contract_codegen.py::diff`` EXACTLY — the same three
checks, in the same order, with the same sha256 and symlink-skip semantics — so
the CI verdict is byte-identical to the in-process pre-PR gate.

  Check 1 — manifest.generatorVersion == the pinned generator version.
  Check 2 — sha256(committed spec) == manifest.specSha.
  Check 3 — relpath -> content map of ``*.swift`` / ``*.java`` (symlinks
            skipped, the ``.contractgen.json`` manifest excluded) under the
            committed tree vs a fresh regeneration: fail on any set difference
            OR any content difference.

Exit codes:
  0  all boundaries conform, OR there are no boundaries (trivial pass), OR the
     generator/spec is unavailable (SKIP).
  1  ANY boundary drifted (the message names the boundary + what drifted).
"""
from __future__ import annotations

import hashlib
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tempfile

# ── Pins (rendered from the MothershipCode contract_codegen constants) ────────
# Lockstep with the openapi-generator the producer used + the manifest stamp.
# These come from build_context (contract_codegen.OPENAPI_GENERATOR_VERSION /
# .OPENAPI_GENERATOR_SHA1) so the gate, the backend image, and the workflow
# fetch all agree on ONE version+sha1. Never hand-edit here.
GENERATOR_VERSION = "7.7.0"

# Pinned sha1 of the openapi-generator JAR (Maven Central's published digest).
# Self-verified here so the SCRIPT — not just the workflow YAML — refuses an
# off-pin JAR: a mismatch means the resolved generator isn't the one every tier
# was built with, so the regenerate verdict would be meaningless. An off-pin JAR
# is a TOOLING problem, not contract drift, so a mismatch routes to the SKIP
# path (exit 0), never a false block. The workflow YAML keeps its own
# ``sha1sum -c`` too (defence in depth).
GENERATOR_SHA1 = "41f26774ba0dbed788613a9c3062ddc6b9fcfdad"

# Models-only invocation — VERBATIM from contract_codegen so the regenerated
# tree matches the committed one byte-for-byte.
MODELS_ONLY_GLOBAL_PROPERTY = (
    "models,modelDocs=false,modelTests=false,"
    "apis=false,apiDocs=false,apiTests=false,supportingFiles=false"
)

# Manifest filename dropped into every generated tree by the engine.
MANIFEST_NAME = ".contractgen.json"

# stack (manifest['stack']) -> openapi-generator ``-g`` value. Matches the
# Swift5CodegenBackend / JavaCodegenBackend registry keys.
STACK_TO_GENERATOR = {"ios": "swift5", "java": "java"}

# Per-generate wall-clock cap (matches the engine).
GENERATE_TIMEOUT_SECONDS = 180

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent


def compute_sha(spec_text: str) -> str:
    """sha256 hex of ``spec_text`` — byte-identical to contract_codegen.compute_sha."""
    return hashlib.sha256((spec_text or "").encode("utf-8")).hexdigest()


def jar_sha1_ok(jar: str) -> bool:
    """True iff ``jar``'s bytes hash to the pinned sha1.

    The script self-verifies the JAR (not just the workflow YAML) so an off-pin
    generator routes to the SKIP path rather than producing a meaningless diff
    verdict. An unreadable JAR returns False (treated as "not the pinned JAR").
    """
    try:
        digest = hashlib.sha1(pathlib.Path(jar).read_bytes()).hexdigest()  # noqa: S324
    except OSError:
        return False
    return digest == GENERATOR_SHA1


def resolve_jar() -> str | None:
    """The openapi-generator JAR from ``OPENAPI_GENERATOR_JAR``, sha1-verified.

    Returns the path only when it exists AND its bytes match the pinned sha1; a
    present-but-off-pin JAR resolves to None → the gate SKIPs (never a false
    block — a wrong-version generator is a tooling problem, not contract drift).
    """
    jar = os.environ.get("OPENAPI_GENERATOR_JAR")
    if jar and pathlib.Path(jar).is_file() and jar_sha1_ok(jar):
        return jar
    return None


def generator_available() -> bool:
    """True only when ``java`` and a sha1-verified pinned JAR are present.

    A missing ``java``, a missing JAR, or a JAR whose sha1 doesn't match the pin
    all yield False → the caller SKIPs (exit 0), never a false block.
    """
    return shutil.which("java") is not None and resolve_jar() is not None


def relative_model_map(root: pathlib.Path) -> dict[str, str]:
    """relpath -> file text for every ``*.swift`` / ``*.java`` under ``root``.

    Symlinks are skipped (a committed tree is untrusted — never follow a
    symlinked source off-tree and read it). The ``.contractgen.json`` manifest
    is a ``*.json`` file, so it is naturally excluded. Mirrors
    contract_codegen._relative_model_map.
    """
    result: dict[str, str] = {}
    if not root.is_dir():
        return result
    for pattern in ("*.swift", "*.java"):
        for path in root.rglob(pattern):
            if path.is_file() and not path.is_symlink():
                result[str(path.relative_to(root))] = path.read_text(
                    encoding="utf-8", errors="replace"
                )
    return result


def read_manifest(out_dir: pathlib.Path) -> dict | None:
    """The committed ``.contractgen.json`` as a dict, or None (matches engine)."""
    manifest_path = out_dir / MANIFEST_NAME
    if not manifest_path.is_file() or manifest_path.is_symlink():
        return None
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    return data if isinstance(data, dict) else None


def discover_boundaries() -> list[tuple[str, pathlib.Path, pathlib.Path]]:
    """Find every candidate boundary on disk — by the UNION of three signals.

    Discovering boundaries ONLY by globbing ``Generated/<slug>/.contractgen.json``
    has a false-pass hole: delete that ONE manifest file (while leaving a
    hand-edited ``Generated/<slug>/Account.swift``) and the boundary vanishes →
    exit 0 — defeating the gate's own "a human edit to a generated DTO is
    caught" promise. So a slug is a candidate if ANY of these exist:

      1. ``Generated/<slug>/.contractgen.json`` (the manifest — the happy path);
      2. ``Generated/<slug>/`` contains a ``*.swift`` / ``*.java`` source (a
         generated tree whose manifest was deleted/lost);
      3. ``contracts/<slug>.openapi.yaml`` (a committed spec whose generated
         tree was deleted).

    Every distinct slug becomes a boundary and is handed to ``check_boundary``,
    which DRIFTS a slug whose tree/spec exists but has no readable manifest (or
    whose spec/tree is missing) — so a partial deletion can no longer silently
    drop the boundary. Returns ``(slug, generated_dir, spec_path)`` tuples; the
    Generated dir and/or spec may not exist for a given slug (``check_boundary``
    turns the absence into drift, not a silent pass).
    """
    generated_root = REPO_ROOT / "Generated"
    contracts_root = REPO_ROOT / "contracts"
    slugs: set[str] = set()

    if generated_root.is_dir():
        for child in generated_root.iterdir():
            if not child.is_dir():
                continue
            # (1) manifest present, OR (2) a generated source file present.
            if (child / MANIFEST_NAME).is_file() or any(
                p.is_file()
                for pattern in ("*.swift", "*.java")
                for p in child.rglob(pattern)
            ):
                slugs.add(child.name)

    if contracts_root.is_dir():
        # (3) a committed spec basename → slug.
        for spec in contracts_root.glob("*.openapi.yaml"):
            slugs.add(spec.name[: -len(".openapi.yaml")])

    out: list[tuple[str, pathlib.Path, pathlib.Path]] = []
    for slug in sorted(slugs):
        gen_dir = generated_root / slug
        spec_path = contracts_root / f"{slug}.openapi.yaml"
        out.append((slug, gen_dir, spec_path))
    return out


def regenerate(spec_path: pathlib.Path, generator: str, out_dir: pathlib.Path) -> None:
    """Run the pinned generator (models-only) into ``out_dir``.

    Builds the EXACT argv contract_codegen.build_command emits. Raises
    RuntimeError on any failure so the caller can SKIP (never a false drift).
    """
    jar = resolve_jar()
    cmd = [
        "java",
        "-jar",
        jar,
        "generate",
        "-i",
        str(spec_path),
        "-g",
        generator,
        "-o",
        str(out_dir),
        "--global-property",
        MODELS_ONLY_GLOBAL_PROPERTY,
    ]
    proc = subprocess.run(  # noqa: S603 — fixed argv, no shell.
        cmd,
        capture_output=True,
        text=True,
        timeout=GENERATE_TIMEOUT_SECONDS,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"openapi-generator failed (exit {proc.returncode}): "
            f"{(proc.stderr or proc.stdout or '').strip()[-500:]}"
        )


def check_boundary(slug: str, gen_dir: pathlib.Path, spec_path: pathlib.Path) -> str | None:
    """Diff one boundary. Returns a drift message (block) or None (conforms).

    Raises RuntimeError when the generator/spec can't run for this boundary so
    the caller can SKIP it. The three checks run in the SAME order as
    contract_codegen.diff: manifest version, spec sha, then the file map.
    """
    if not spec_path.is_file():
        raise RuntimeError(
            f"committed spec {spec_path.relative_to(REPO_ROOT)} is missing"
        )
    spec_text = spec_path.read_text(encoding="utf-8")

    manifest = read_manifest(gen_dir)
    if manifest is None:
        # Discovery enumerates the UNION of (manifest, generated source, spec), so
        # a slug can reach here with NO readable manifest — a deleted/unreadable/
        # non-object ``.contractgen.json`` over a still-committed tree/spec. Treat
        # as drift (not a silent pass): the gate's whole point is that a generated
        # tree must carry the manifest that proves how it was made.
        return (
            f"boundary '{slug}': Generated/{slug}/{MANIFEST_NAME} is missing or "
            "not a JSON object — the generated tree is not a valid MothershipCode "
            "manifest (was it deleted or hand-edited?). Re-generate from the "
            "committed spec."
        )

    stack = manifest.get("stack")
    generator = STACK_TO_GENERATOR.get(stack)
    if generator is None:
        raise RuntimeError(
            f"boundary '{slug}': manifest stack {stack!r} has no known generator"
        )

    # ── Check 1: pinned generator version (after we know we CAN regenerate).
    if manifest.get("generatorVersion") != GENERATOR_VERSION:
        return (
            f"boundary '{slug}': manifest generatorVersion "
            f"{manifest.get('generatorVersion')!r} != pinned {GENERATOR_VERSION!r} "
            "— regenerate with the pinned openapi-generator."
        )

    # ── Check 2: committed spec sha matches the manifest stamp.
    if compute_sha(spec_text) != manifest.get("specSha"):
        return (
            f"boundary '{slug}': sha256(contracts/{slug}.openapi.yaml) != "
            "manifest.specSha — the committed spec was changed without "
            "regenerating the types (or the spec/manifest drifted)."
        )

    # ── Check 3: fresh regeneration's file map == the committed file map.
    tmp_root = pathlib.Path(tempfile.mkdtemp(prefix=f"contract-gate-{slug}-"))
    try:
        regenerate(spec_path, generator, tmp_root)
        fresh = relative_model_map(tmp_root)
        committed = relative_model_map(gen_dir)

        if set(fresh) != set(committed):
            added = sorted(set(fresh) - set(committed))
            removed = sorted(set(committed) - set(fresh))
            return (
                f"boundary '{slug}': generated file SET drifted. "
                f"Missing from commit: {added or '[]'}. "
                f"Should not be committed: {removed or '[]'}. "
                "Re-generate; never hand-edit Generated/."
            )
        for rel, fresh_text in fresh.items():
            if fresh_text != committed.get(rel):
                return (
                    f"boundary '{slug}': Generated/{slug}/{rel} differs from a "
                    "fresh generation — the committed type was hand-edited or is "
                    "stale. Generated/ is regenerated, never edited."
                )
        return None
    finally:
        shutil.rmtree(tmp_root, ignore_errors=True)


def main() -> int:
    boundaries = discover_boundaries()
    if not boundaries:
        # Trivially passes ONLY when BOTH Generated/ and contracts/ are genuinely
        # empty of slugs — a deleted manifest over a still-committed tree/spec is
        # discovered (and drifts) above, never silently dropped here.
        print("contract-gate: no boundaries found — Generated/ and contracts/ "
              "carry no contract slug (no manifest, generated source, or spec). "
              "Nothing to check (pass).")
        return 0

    if not generator_available():
        print(
            "contract-gate: SKIP — java is missing, or $OPENAPI_GENERATOR_JAR is "
            "absent / does not match the pinned openapi-generator sha1 "
            f"({GENERATOR_SHA1}), so the gate cannot re-generate with the pinned "
            "toolchain. An off-pin JAR is a tooling problem, not contract drift — "
            "the in-process pre-PR gate remains the primary enforcement. "
            f"(boundaries on disk: {[b[0] for b in boundaries]})"
        )
        return 0

    drifted: list[str] = []
    for slug, gen_dir, spec_path in boundaries:
        try:
            message = check_boundary(slug, gen_dir, spec_path)
        except RuntimeError as exc:
            # Generator/spec unavailable for THIS boundary → SKIP it (never a
            # false block), mirroring the engine's CodegenError == SKIP.
            print(f"contract-gate: SKIP boundary '{slug}' — {exc}")
            continue
        if message is None:
            print(f"contract-gate: OK — boundary '{slug}' conforms.")
        else:
            print(f"contract-gate: DRIFT — {message}")
            drifted.append(slug)

    if drifted:
        print(
            "\ncontract-gate: FAILED — contract drift detected in: "
            f"{', '.join(drifted)}. Regenerate the types from the committed spec "
            "(do not hand-edit Generated/)."
        )
        return 1
    print("\ncontract-gate: PASSED — all boundaries conform.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
